Update description for PackedElementField
foxglove/schemas pull request #26
Opened 2022-05-17 22:08 UTC by jtbandes

**Public-Facing Changes**
Updated description for PackedElementField

2022-05-17 22:15 UTC, defunctzombie approved these changes

2022-05-17 22:22 UTC, esthersweon requested changes
Suggested changes to description.

2022-05-17 22:22 UTC, esthersweon commented on schemas/jsonschema/Grid.json
> +        "description": "Defines a field within packed data. Commonly used to represent a field of a single element within a byte array containing multiple packed elements.",
Can remove "Defines" from beginning of every version of this schema. Don't think the other schemas are formatted this way.

2022-05-17 22:22 UTC, esthersweon commented on schemas/jsonschema/Grid.json
> +        "description": "Defines a field within packed data. Commonly used to represent a field of a single element within a byte array containing multiple packed elements.",
```suggestion
  "description": "A field present within each element in a byte array of packed elements.",
```

2022-05-17 22:26 UTC, esthersweon commented on schemas/jsonschema/Grid.json
> +        "description": "Defines a field within packed data. Commonly used to represent a field of a single element within a byte array containing multiple packed elements.",
Or maybe even "each packed element in a byte array".

2022-05-18 21:03 UTC, esthersweon approved these changes

2022-05-18 21:38 UTC, merged