Add supported encoding formats to RawImage and CompressedImage
foxglove/schemas pull request #33
Opened 2022-05-20 01:35 UTC by esthersweon

**Public-Facing Changes**
- Add supported encoding formats to RawImage and CompressedImage 

Resolves #32

2022-05-20 02:38 UTC, jtbandes approved these changes

2022-05-20 04:09 UTC, amacneil approved these changes

2022-06-14 05:24 UTC, amacneil commented
ready to merge?

2022-08-06 00:23 UTC, amacneil requested changes
On second thoughts, I do not think we should have two sources of truth on this in our docs. It seems inevitable that someone will add support for a new format, and update one of these lists but not the other (especially since they live in separate repos).

I would prefer something like:

```
[Image format](https://foxglove.dev/docs/studio/panels/image#supported-encoding-formats)
```

It won't look as great in generated schema source code, but is obvious enough, and will improve the website docs.

2022-08-30 00:18 UTC, esthersweon commented
Closing this PR, and addressing in https://github.com/foxglove/schemas/pull/60.

2022-08-30 00:18 UTC, closed without merging